<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
* { box-sizing: border-box; }
body {
    font-family: 'DejaVu Sans', sans-serif;
    font-size: 9pt;
    color: #1e293b;
    background: #fff;
    margin: 0;
    padding: 24px 28px 28px;
}

/* ── Letterhead / header ── */
.hdr-table { width: 100%; border-collapse: collapse; margin-bottom: 6px; }
.hdr-logo  { width: 90px; vertical-align: middle; }
.hdr-logo img { max-width: 80px; max-height: 60px; }
.hdr-text  { vertical-align: middle; padding-left: 12px; }
.hdr-brand { font-size: 14pt; font-weight: bold; color: #15803d; letter-spacing: .5px; }
.hdr-sub   { font-size: 7.5pt; color: #64748b; margin-top: 2px; }
.hdr-meta  { vertical-align: middle; text-align: right; font-size: 7.5pt; color: #64748b; }
.hdr-meta strong { color: #1e293b; }

.divider { border: none; border-top: 2px solid #15803d; margin: 8px 0 12px; }

/* ── Page title ── */
.page-title { font-size: 13pt; font-weight: bold; color: #0f172a; margin: 0 0 2px; }
.page-sub   { font-size: 8pt; color: #64748b; margin: 0 0 12px; }

/* ── Patient info box ── */
.patient-box {
    background: #f0fdf4;
    border: 1px solid #bbf7d0;
    border-radius: 4px;
    padding: 8px 12px;
    margin-bottom: 14px;
}
.patient-grid { width: 100%; border-collapse: collapse; }
.patient-grid td { font-size: 8pt; padding: 2px 8px 2px 0; vertical-align: top; }
.patient-label { color: #64748b; font-weight: bold; text-transform: uppercase; letter-spacing: .04em; font-size: 6.5pt; width: 80px; }
.patient-value { color: #0f172a; font-weight: bold; }

/* ── Section title ── */
.section-title {
    font-size: 8pt; font-weight: bold; text-transform: uppercase;
    letter-spacing: .07em; color: #fff;
    background: #15803d; padding: 4px 10px;
    margin: 14px 0 0;
}

/* ── Results table ── */
table.calc-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 4px;
}
table.calc-table th {
    background: #f1f5f9;
    font-size: 7pt;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: .05em;
    color: #475569;
    padding: 4px 6px;
    text-align: left;
    border-bottom: 1.5px solid #cbd5e1;
}
table.calc-table th.right,
table.calc-table td.right { text-align: right; }
table.calc-table td {
    font-size: 8pt;
    padding: 4px 6px;
    border-bottom: 1px solid #f1f5f9;
    color: #1e293b;
    vertical-align: top;
}
table.calc-table tr.alt td { background: #f8fafc; }
.sub-val { font-size: 6.5pt; color: #94a3b8; margin-top: 1px; }
.badge-green {
    background: #dcfce7; color: #15803d;
    padding: 1px 5px; border-radius: 2px;
    font-size: 7pt; font-weight: bold;
}

/* ── Macro mini-table per calc ── */
table.macro-mini {
    width: 100%; border-collapse: collapse;
    margin-top: 5px;
    border: 1px solid #e2e8f0;
}
table.macro-mini th {
    background: #f8fafc; font-size: 6.5pt; font-weight: bold;
    text-transform: uppercase; letter-spacing: .04em; color: #94a3b8;
    padding: 3px 5px; border-bottom: 1px solid #e2e8f0; text-align: left;
}
table.macro-mini td {
    font-size: 7.5pt; padding: 3px 5px;
    border-bottom: 1px solid #f1f5f9;
    color: #1e293b;
}
table.macro-mini td.right { text-align: right; }
table.macro-mini tr:last-child td { border-bottom: none; }

/* ── Disclaimer ── */
.disclaimer {
    font-size: 6.5pt; color: #94a3b8; line-height: 1.5;
    border-top: 1px solid #e2e8f0; margin-top: 18px; padding-top: 6px;
}

/* ── Empty state ── */
.empty { font-size: 9pt; color: #94a3b8; padding: 20px 0; text-align: center; }
</style>
</head>
<body>

{{-- ── Header ─────────────────────────────────────────────────────────── --}}
<table class="hdr-table">
    <tr>
        @if($letterhead)
        <td class="hdr-logo">
            <img src="{{ $letterhead }}" alt="">
        </td>
        @endif
        <td class="hdr-text">
            <div class="hdr-brand">MindfulNutrico</div>
            <div class="hdr-sub">Enteral Nutrition Calculator &mdash; SASPEN / ESPEN Guidelines</div>
        </td>
        <td class="hdr-meta">
            <strong>{{ now()->format('d F Y') }}</strong><br>
            Generated by {{ auth()->user()->name }}
        </td>
    </tr>
</table>
<hr class="divider">

{{-- ── Page title ─────────────────────────────────────────────────────── --}}
<div class="page-title">Tube Feed Prescription</div>
<div class="page-sub">Enteral Nutrition Calculation Report</div>

{{-- ── Patient demographics ─────────────────────────────────────────── --}}
<div class="patient-box">
    <table class="patient-grid">
        <tr>
            <td class="patient-label">Patient</td>
            <td class="patient-value">{{ $patient->full_name }}</td>
            <td class="patient-label">Gender</td>
            <td class="patient-value">{{ ucfirst($patient->gender ?? '—') }}</td>
            <td class="patient-label">Age</td>
            <td class="patient-value">{{ $patient->age ? $patient->age . ' yrs' : '—' }}</td>
        </tr>
        <tr>
            <td class="patient-label">Weight</td>
            <td class="patient-value">{{ $patient->weight ? $patient->weight . ' kg' : '—' }}</td>
            <td class="patient-label">Height</td>
            <td class="patient-value">{{ $patient->height ? $patient->height . ' cm' : '—' }}</td>
            <td class="patient-label">BMI</td>
            <td class="patient-value">{{ $patient->bmi ? number_format($patient->bmi, 1) . ' kg/m²' : '—' }}</td>
        </tr>
    </table>
</div>

{{-- ── Calculations ─────────────────────────────────────────────────── --}}
@if($calculations->isEmpty())
    <div class="empty">No saved calculations for this patient.</div>
@else
    @php
        $formulaDb = [
            '1.0' => ['proteinGL' => 40.0,  'carbsGL' => 127.0, 'fatGL' => 35.4, 'freeWater' => 0.85],
            '1.2' => ['proteinGL' => 55.5,  'carbsGL' => 169.4, 'fatGL' => 39.3, 'freeWater' => 0.80],
            '1.5' => ['proteinGL' => 62.0,  'carbsGL' => 200.0, 'fatGL' => 50.0, 'freeWater' => 0.70],
        ];
    @endphp

    @foreach($calculations as $i => $calc)
        @php
            $density   = (string)number_format((float)$calc->formula_density, 1);
            $formula   = $formulaDb[$density] ?? $formulaDb['1.0'];
            $volumeL   = $calc->daily_volume_ml / 1000;
            $fmlPro    = round($volumeL * $formula['proteinGL'], 1);
            $fmlCarbs  = round($volumeL * $formula['carbsGL'], 1);
            $fmlFat    = round($volumeL * $formula['fatGL'], 1);
            $fwMl      = round($calc->daily_volume_ml * $formula['freeWater']);
            $adequate  = $fmlPro >= $calc->protein_target_g;

            $heightCm  = (float)($patient->height ?? 0);
            $age       = (int)($patient->age ?? 0);
            $isMale    = strtolower($patient->gender ?? 'male') !== 'female';
            $wt        = (float)$calc->weight_kg;
            $ree = ($heightCm > 0 && $age > 0)
                ? round(($isMale
                    ? (10*$wt) + (6.25*$heightCm) - (5*$age) + 5
                    : (10*$wt) + (6.25*$heightCm) - (5*$age) - 161))
                : null;

            $flushPerFeed = $calc->additional_water_ml > 0 ? round($calc->additional_water_ml / 6) : 0;
        @endphp

        <div class="section-title">
            Calculation #{{ $i + 1 }}
            @if($calc->label) &mdash; {{ $calc->label }} @endif
            &nbsp;&nbsp;
            <span style="font-weight:normal;font-size:7pt;letter-spacing:0">{{ $calc->created_at->format('d M Y H:i') }}</span>
        </div>

        {{-- Primary results ── --}}
        <table class="calc-table">
            <thead>
                <tr>
                    <th>Parameter</th>
                    <th class="right">Value</th>
                    <th>Parameter</th>
                    <th class="right">Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Weight Used</td>
                    <td class="right">
                        <strong>{{ number_format($calc->weight_kg, 1) }} kg</strong>
                        <div class="sub-val">{{ strtoupper($calc->weight_type) }}</div>
                    </td>
                    <td>Formula Density</td>
                    <td class="right"><strong>{{ number_format((float)$calc->formula_density, 1) }} kcal/mL</strong></td>
                </tr>
                <tr class="alt">
                    <td>Energy Target</td>
                    <td class="right">
                        <strong>{{ number_format($calc->energy_target_kcal, 0) }} kcal/day</strong>
                        <div class="sub-val">{{ $calc->energy_kcal_per_kg }} kcal/kg/day</div>
                    </td>
                    <td>Feed Duration</td>
                    <td class="right"><strong>{{ $calc->feeding_hours_per_day }} hrs/day</strong></td>
                </tr>
                <tr>
                    <td>Protein Target</td>
                    <td class="right">
                        <strong>{{ number_format($calc->protein_target_g, 1) }} g/day</strong>
                        <div class="sub-val">{{ $calc->protein_g_per_kg }} g/kg/day</div>
                    </td>
                    <td>Daily Volume</td>
                    <td class="right"><strong>{{ number_format($calc->daily_volume_ml, 0) }} mL/day</strong></td>
                </tr>
                <tr class="alt">
                    <td>Infusion Rate</td>
                    <td class="right"><strong>{{ number_format($calc->rate_ml_per_hour, 1) }} mL/hr</strong></td>
                    <td>Additional Water</td>
                    <td class="right">
                        <strong>{{ number_format($calc->additional_water_ml, 0) }} mL/day</strong>
                        @if($flushPerFeed > 0)
                            <div class="sub-val">{{ $flushPerFeed }} mL &times; 6 flushes</div>
                        @endif
                    </td>
                </tr>
                <tr>
                    <td>Free Water from Formula</td>
                    <td class="right"><strong>{{ number_format($fwMl, 0) }} mL</strong></td>
                    <td>Fluid Requirement (35 mL/kg)</td>
                    <td class="right"><strong>{{ number_format($calc->fluid_requirement_ml, 0) }} mL</strong></td>
                </tr>
                @if($ree)
                <tr class="alt">
                    <td>REE &mdash; Mifflin-St Jeor</td>
                    <td class="right"><strong>{{ number_format($ree, 0) }} kcal/day</strong></td>
                    <td>Nitrogen</td>
                    <td class="right"><strong>{{ round($calc->protein_target_g / 6.25, 1) }} g/day</strong></td>
                </tr>
                @endif
            </tbody>
        </table>

        {{-- Formula macros ── --}}
        <table class="macro-mini">
            <thead>
                <tr>
                    <th>Formula Macros per Daily Volume ({{ number_format($calc->daily_volume_ml) }} mL)</th>
                    <th class="right">Protein</th>
                    <th class="right">Carbohydrates</th>
                    <th class="right">Fat</th>
                    <th>Protein adequacy</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ number_format((float)$calc->formula_density, 1) }} kcal/mL formula</td>
                    <td class="right"><strong>{{ $fmlPro }} g</strong></td>
                    <td class="right"><strong>{{ $fmlCarbs }} g</strong></td>
                    <td class="right"><strong>{{ $fmlFat }} g</strong></td>
                    <td>
                        @if($adequate)
                            <span class="badge-green">&#10003; Meets goal</span>
                        @else
                            <span style="font-size:7pt;color:#b91c1c;font-weight:bold;">
                                &#9888; Below goal ({{ number_format($calc->protein_target_g, 1) }} g needed)
                            </span>
                        @endif
                    </td>
                </tr>
            </tbody>
        </table>

        {{-- Start-up guidance ── --}}
        <div style="font-size:7.5pt;color:#475569;margin-top:6px;padding:5px 8px;background:#f8fafc;border:1px solid #e2e8f0;">
            <strong>Start-up protocol:</strong>
            Start at 20 mL/hr, titrate by 10&ndash;20 mL/hr every 4 hours to goal rate of
            <strong>{{ number_format($calc->rate_ml_per_hour, 1) }} mL/hr</strong>.
            @if($calc->additional_water_ml > 0)
                Flush with <strong>{{ $flushPerFeed }} mL</strong> water 6&times;/day (total {{ number_format($calc->additional_water_ml) }} mL).
            @endif
        </div>

        @if($calc->notes)
        <div style="font-size:7.5pt;color:#1e293b;margin-top:5px;padding:4px 8px;background:#fffbeb;border:1px solid #fde68a;">
            <strong>Notes:</strong> {{ $calc->notes }}
        </div>
        @endif

    @endforeach
@endif

{{-- ── Disclaimer ───────────────────────────────────────────────────── --}}
<div class="disclaimer">
    This report is generated from MindfulNutrico and is intended for use by registered dieticians only.
    Calculations are based on SASPEN/ESPEN guidelines and generic enteral formula data.
    Verify all values against current product datasheets and clinical status before prescribing.
    Manufacturers may change formula composition at any time.
</div>

</body>
</html>
