<?php

/**
 * Standard dietary exchange template presets.
 *
 * Each preset defines:
 *   - name          : display name
 *   - description   : short description shown in the picker
 *   - kcal_target   : approximate daily energy target
 *   - items[]       : exchange groups with nu (total daily exchanges) and
 *                     per-slot breakdown that sums to nu.
 *                     Slots: breakfast | snack1 | lunch | snack2 | supper | snack3
 *   - macros[]      : optional rough macro targets (not applied automatically)
 *
 * Item nutrient values (cho_g, protein_min_g, protein_max_g, fat_min_g,
 * fat_max_g, kj) are kept from whatever the patient's exchange template
 * already has for items with matching names — only nu and slots are
 * overwritten.  For items that don't yet exist they will be created with
 * the values specified here.
 */

return [

    // ─────────────────────────────────────────────────────────────────────────
    // 1. Standard Balanced Diet  (~1 800 kcal)
    // ─────────────────────────────────────────────────────────────────────────
    'balanced' => [
        'name'        => 'Standard Balanced Diet',
        'description' => 'Normal healthy adult — ~1 800 kcal balanced macros',
        'kcal_target' => 1800,
        'items' => [
            [
                'name'          => 'Starch',
                'nu'            => 7,
                'cho_g'         => 15,
                'protein_min_g' => 0,
                'protein_max_g' => 3,
                'fat_min_g'     => 0,
                'fat_max_g'     => 1,
                'kj'            => 335,
                'slot_breakfast'=> 2,
                'slot_snack1'   => 1,
                'slot_lunch'    => 2,
                'slot_snack2'   => 0,
                'slot_supper'   => 2,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Fruit',
                'nu'            => 2,
                'cho_g'         => 15,
                'protein_min_g' => null,
                'protein_max_g' => null,
                'fat_min_g'     => null,
                'fat_max_g'     => null,
                'kj'            => 250,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 1,
                'slot_lunch'    => 0,
                'slot_snack2'   => 0,
                'slot_supper'   => 0,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Veg, free veg',
                'nu'            => 3,
                'cho_g'         => 5,
                'protein_min_g' => 2,
                'protein_max_g' => 2,
                'fat_min_g'     => null,
                'fat_max_g'     => null,
                'kj'            => 105,
                'slot_breakfast'=> 0,
                'slot_snack1'   => 0,
                'slot_lunch'    => 1,
                'slot_snack2'   => 0,
                'slot_supper'   => 2,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Milk, low fat',
                'nu'            => 2,
                'cho_g'         => 12,
                'protein_min_g' => 8,
                'protein_max_g' => 8,
                'fat_min_g'     => 5,
                'fat_max_g'     => 5,
                'kj'            => 500,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 1,
                'slot_lunch'    => 0,
                'slot_snack2'   => 0,
                'slot_supper'   => 0,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Meat, lean fat',
                'nu'            => 5,
                'cho_g'         => null,
                'protein_min_g' => 7,
                'protein_max_g' => 7,
                'fat_min_g'     => 0,
                'fat_max_g'     => 3,
                'kj'            => 190,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 0,
                'slot_lunch'    => 2,
                'slot_snack2'   => 0,
                'slot_supper'   => 2,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Fat',
                'nu'            => 3,
                'cho_g'         => null,
                'protein_min_g' => null,
                'protein_max_g' => null,
                'fat_min_g'     => 5,
                'fat_max_g'     => 5,
                'kj'            => 190,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 0,
                'slot_lunch'    => 1,
                'slot_snack2'   => 0,
                'slot_supper'   => 1,
                'slot_snack3'   => 0,
            ],
        ],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    // 2. Diabetes Meal Exchange  (~1 800 kcal)
    // ─────────────────────────────────────────────────────────────────────────
    'diabetes' => [
        'name'        => 'Diabetes Meal Exchange',
        'description' => 'Controlled carbohydrate — ~1 800 kcal diabetic plan',
        'kcal_target' => 1800,
        'items' => [
            [
                'name'          => 'Starch',
                'nu'            => 7,
                'cho_g'         => 15,
                'protein_min_g' => 0,
                'protein_max_g' => 3,
                'fat_min_g'     => 0,
                'fat_max_g'     => 1,
                'kj'            => 335,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 1,
                'slot_lunch'    => 2,
                'slot_snack2'   => 0,
                'slot_supper'   => 2,
                'slot_snack3'   => 1,
            ],
            [
                'name'          => 'Fruit',
                'nu'            => 2,
                'cho_g'         => 15,
                'protein_min_g' => null,
                'protein_max_g' => null,
                'fat_min_g'     => null,
                'fat_max_g'     => null,
                'kj'            => 250,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 0,
                'slot_lunch'    => 0,
                'slot_snack2'   => 1,
                'slot_supper'   => 0,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Veg, free veg',
                'nu'            => 4,
                'cho_g'         => 5,
                'protein_min_g' => 2,
                'protein_max_g' => 2,
                'fat_min_g'     => null,
                'fat_max_g'     => null,
                'kj'            => 105,
                'slot_breakfast'=> 0,
                'slot_snack1'   => 0,
                'slot_lunch'    => 2,
                'slot_snack2'   => 0,
                'slot_supper'   => 2,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Milk, low fat',
                'nu'            => 2,
                'cho_g'         => 12,
                'protein_min_g' => 8,
                'protein_max_g' => 8,
                'fat_min_g'     => 5,
                'fat_max_g'     => 5,
                'kj'            => 500,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 0,
                'slot_lunch'    => 0,
                'slot_snack2'   => 1,
                'slot_supper'   => 0,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Meat, lean fat',
                'nu'            => 5,
                'cho_g'         => null,
                'protein_min_g' => 7,
                'protein_max_g' => 7,
                'fat_min_g'     => 0,
                'fat_max_g'     => 3,
                'kj'            => 190,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 0,
                'slot_lunch'    => 2,
                'slot_snack2'   => 0,
                'slot_supper'   => 2,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Fat',
                'nu'            => 3,
                'cho_g'         => null,
                'protein_min_g' => null,
                'protein_max_g' => null,
                'fat_min_g'     => 5,
                'fat_max_g'     => 5,
                'kj'            => 190,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 1,
                'slot_lunch'    => 1,
                'slot_snack2'   => 0,
                'slot_supper'   => 1,
                'slot_snack3'   => 0,
            ],
        ],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    // 3. Renal Diet (CKD)  (~1 800 kcal)
    // ─────────────────────────────────────────────────────────────────────────
    'renal' => [
        'name'        => 'Renal Diet (CKD)',
        'description' => 'Chronic Kidney Disease — controlled protein, K⁺ & P',
        'kcal_target' => 1800,
        'items' => [
            [
                'name'          => 'Starch',
                'nu'            => 7,
                'cho_g'         => 15,
                'protein_min_g' => 0,
                'protein_max_g' => 3,
                'fat_min_g'     => 0,
                'fat_max_g'     => 1,
                'kj'            => 335,
                'slot_breakfast'=> 2,
                'slot_snack1'   => 0,
                'slot_lunch'    => 2,
                'slot_snack2'   => 1,
                'slot_supper'   => 2,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Fruit',
                'nu'            => 2,
                'cho_g'         => 15,
                'protein_min_g' => null,
                'protein_max_g' => null,
                'fat_min_g'     => null,
                'fat_max_g'     => null,
                'kj'            => 250,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 0,
                'slot_lunch'    => 0,
                'slot_snack2'   => 1,
                'slot_supper'   => 0,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Veg, free veg',
                'nu'            => 2,
                'cho_g'         => 5,
                'protein_min_g' => 2,
                'protein_max_g' => 2,
                'fat_min_g'     => null,
                'fat_max_g'     => null,
                'kj'            => 105,
                'slot_breakfast'=> 0,
                'slot_snack1'   => 1,
                'slot_lunch'    => 1,
                'slot_snack2'   => 0,
                'slot_supper'   => 1,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Meat, lean fat',
                'nu'            => 3,
                'cho_g'         => null,
                'protein_min_g' => 7,
                'protein_max_g' => 7,
                'fat_min_g'     => 0,
                'fat_max_g'     => 3,
                'kj'            => 190,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 0,
                'slot_lunch'    => 1,
                'slot_snack2'   => 0,
                'slot_supper'   => 1,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Milk, low fat',
                'nu'            => 1,
                'cho_g'         => 12,
                'protein_min_g' => 8,
                'protein_max_g' => 8,
                'fat_min_g'     => 5,
                'fat_max_g'     => 5,
                'kj'            => 500,
                'slot_breakfast'=> 0,
                'slot_snack1'   => 0,
                'slot_lunch'    => 0,
                'slot_snack2'   => 0,
                'slot_supper'   => 1,
                'slot_snack3'   => 0,
            ],
            [
                'name'          => 'Fat',
                'nu'            => 5,
                'cho_g'         => null,
                'protein_min_g' => null,
                'protein_max_g' => null,
                'fat_min_g'     => 5,
                'fat_max_g'     => 5,
                'kj'            => 190,
                'slot_breakfast'=> 1,
                'slot_snack1'   => 1,
                'slot_lunch'    => 1,
                'slot_snack2'   => 1,
                'slot_supper'   => 2,
                'slot_snack3'   => 0,
            ],
        ],
    ],

];
